/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attackgame.View;

import java.awt.*;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author joris
 */
public class MenuTest extends javax.swing.JFrame {

    /**
     * Creates new form MenuTest
     */
    //Variable declaration
    int levelChoice = 0; //Ou String à voir 

    public MenuTest() {
        initComponents();
        this.setSize(this.getWidth(), this.getHeight());
        for (int i = 5; i <= 200; i += 5) {
            choiceRow.add(String.valueOf(i));
            choiceColumn.add(String.valueOf(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Level3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Level1 = new javax.swing.JButton();
        Level2 = new javax.swing.JButton();
        choiceColumn = new java.awt.Choice();
        choiceRow = new java.awt.Choice();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        play = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        Level3.setText("Level 3");
        Level3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level3ActionPerformed(evt);
            }
        });
        getContentPane().add(Level3);
        Level3.setBounds(110, 180, 88, 29);

        jLabel1.setText("Choose your level :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 100, 130, 16);

        Level1.setText("Level 1");
        Level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level1ActionPerformed(evt);
            }
        });
        getContentPane().add(Level1);
        Level1.setBounds(110, 120, 88, 29);

        Level2.setText("Level 2");
        Level2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level2ActionPerformed(evt);
            }
        });
        getContentPane().add(Level2);
        Level2.setBounds(110, 150, 88, 29);
        getContentPane().add(choiceColumn);
        choiceColumn.setBounds(180, 60, 60, 20);
        getContentPane().add(choiceRow);
        choiceRow.setBounds(90, 60, 60, 20);

        jLabel2.setText("x");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 60, 10, 16);

        jLabel3.setText("Choose the map size :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 30, 140, 16);

        play.setText("PLAY");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(100, 220, 97, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Level3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level3ActionPerformed
        // TODO add your handling code here:
        System.out.println("Level 3 selected");
        levelChoice = 3;
        Level1.setBackground(new Color(238, 238, 238));
        Level2.setBackground(new Color(238, 238, 238));
        Level3.setBackground(Color.yellow);
    }//GEN-LAST:event_Level3ActionPerformed

    private void Level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Level 1 selected");
        levelChoice = 1;
        Level1.setBackground(Color.yellow);
        Level2.setBackground(new Color(238, 238, 238));
        Level3.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_Level1ActionPerformed

    private void Level2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level2ActionPerformed
        // TODO add your handling code here:
        System.out.println("Level 2 selected");
        levelChoice = 2;
        Level1.setBackground(new Color(238, 238, 238));
        Level2.setBackground(Color.yellow);
        Level3.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_Level2ActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        if (levelChoice == 0) {
            JOptionPane.showMessageDialog(this, "Please, select a level.");
        } else {
            //Lancer le niveau en fonction du level choisi
            System.out.println("Lancement Level n°" + levelChoice);
        }
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Level1;
    public javax.swing.JButton Level2;
    public javax.swing.JButton Level3;
    public java.awt.Choice choiceColumn;
    public java.awt.Choice choiceRow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
